apiVersion: v1 
kind: ServiceAccount
metadata:
  name: catalogue-serviceaccount
  namespace: roboshop
  labels: 
    project: roboshop
    component: catalogue
    tier: backend
  annotations:
    azure.workload.identity/client-id: ""
